---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

  vars:
    apache_mods_enabled:
        - ssl
    apache_create_vhosts: true
    apache_vhosts_filename: "mysite.conf"
    apache_vhost_config:
      - listen_ip: "*"
        listen_port: 80
        server_name: host1
        custom_param: |
          Redirect / https://host1

      - listen_ip: "*"
        listen_port: 443
        server_name: host1
        serveralias: alias1
        documentroot: "/var/www/html"
        serveradmin: admin@localhost
        custom_param: |
          ProxyRequests Off
          ProxyPreserveHost On
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
          LogLevel warn
        ssl_engine: "on"
        ssl_certificate_file: /etc/ssl/certs/certif.crt
        ssl_certificate_key_file: /etc/ssl/private/certif.key
        ssl_certificate_chain_file: /etc/ssl/certs/chain
        directory:
          - path: "/var/www/html"
            config: |
              AllowOverride All
              Order deny,allow
              allow from all

  roles:
    - role: supertarto.apache
